### ISSUE TITLE
附加需求

### ISSUE THREAD

**Issue by Zvirtuey** [shaoshuai904/XStyleDialog#2]
1.AlertEditDialog输入框那个弹窗能添加2个输入框吗
2.ActionSheetDialog能增加一种居中显示吗

**Comment by shaoshuai904** [comment]
1. 需要多表单填写的时候，跳转到某个页面是不是更好。
2.整体直接居中，应该不好看吧，我这里没有具体的参考图，以方便设计更精美的UI. 你那里有么
