### ISSUE TITLE
请问如何设定从顶部弹出。吸顶操作。谢谢

### ISSUE THREAD

**Issue by Danniel-yan** [shaoshuai904/XStyleDialog#4]

**Comment by shaoshuai904** [comment]
window.setGravity(Gravity.START or Gravity.TOP)，可以设置显示在顶部，
但是需要重写布局，基本上Dialog 都是居中和底部，
顶部和基于特定view的一般都用PopupWindow，[https://github.com/shaoshuai904/MsPopupWindow](https://github.com/shaoshuai904/MsPopupWindow)
